name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "macOS-Release",
            os: macos-latest,
            cmake_opts: "-DALSOFT_REQUIRE_COREAUDIO=ON \
              -DALSOFT_TESTS=ON",
            build_type: "Release"
          }
        - {
            name: "iOS-Release",
            os: macos-latest,
            cmake_opts: "-GXcode \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DALSOFT_REQUIRE_COREAUDIO=ON \
            -DALSOFT_UTILS=OFF \
            -DALSOFT_EXAMPLES=OFF \
            -DALSOFT_TESTS=OFF \
            -DALSOFT_INSTALL=OFF \
            \"-DCMAKE_OSX_ARCHITECTURES=arm64\"",
            build_type: "Release"
          }

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      shell: bash
      run: |
        if [[ ! -z "${{matrix.config.deps_cmdline}}" ]]; then
          eval ${{matrix.config.deps_cmdline}}
        fi

    - name: Configure
      shell: bash
      run: |
        cmake -B build -DLIBTYPE=STATIC -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} ${{matrix.config.cmake_opts}} .

    - name: Build
      shell: bash
      run: |
        cmake --build build --config ${{matrix.config.build_type}}

    - name: Test
      shell: bash
      run: |
        cd build
        ctest

    - name: Create Archive
      if: ${{ matrix.config.os == 'macos-latest' }}
      shell: bash
      run: |
        cd build
        mkdir archive
        cp *.a archive/

    - name: Upload Archive
      uses: actions/upload-artifact@v3.1.2
      if: ${{ matrix.config.os == 'macos-latest' }}
      with:
        name: soft_oal-${{matrix.config.name}}
        path: build/archive
